---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: operator.redhatgov.io/workshop-operator:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/operator_v1_workshop_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the operator.redhatgov.io/v1.Workshop
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/operator_v1_workshop_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='operator.redhatgov.io', api_version='v1', kind='Workshop', namespace=namespace, resource_name=custom_resource.metadata.name) }}"

  - name: Wait 40s for reconcilation to run
    k8s_facts:
      api_version: 'v1'
      kind: 'Workshop'
      namespace: '{{ namespace }}'
      name: '{{ custom_resource.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 4
    retries: 10

- import_playbook: "{{ playbook_dir }}/../default/asserts.yml"
